name: Greet
on:
  pull_request_target:

permissions: {}

concurrency:
  group: greet-${{ github.ref }}

jobs:
  greet:
    name: Greet
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Thanks for ${{ github.event.pull_request.title }}"
          echo "done"
